name: hydroecolstm_env
channels:
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0=py310haa95532_0
  - aiohttp=3.10.5=py310h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.16=py310haa95532_0
  - arrow=1.3.0=py310haa95532_0
  - astroid=3.2.4=py310haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310haa95532_0
  - asyncssh=2.17.0=py310haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=24.2.0=py310haa95532_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.11.0=py310haa95532_0
  - beautifulsoup4=4.12.3=py310haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.8.0=py310haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py310haa95532_0
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py310hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - certifi=2024.8.30=py310haa95532_0
  - cffi=1.17.1=py310h827c3e9_0
  - chardet=4.0.0=py310haa95532_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py310haa95532_0
  - cloudpickle=3.0.0=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - contourpy=1.2.0=py310h59b6b97_0
  - cookiecutter=2.6.0=py310haa95532_0
  - cryptography=43.0.3=py310hbd6ee87_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py310haa95532_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.8=py310haa95532_0
  - docstring-to-markdown=0.11=py310haa95532_0
  - docutils=0.18.1=py310haa95532_3
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py310haa95532_0
  - flake8=7.1.1=py310haa95532_0
  - fonttools=4.51.0=py310h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.5.0=py310h827c3e9_0
  - fsspec=2024.6.1=py310haa95532_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=py310haa95532_0
  - imagesize=1.4.1=py310haa95532_0
  - importlib-metadata=7.0.1=py310haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - inflection=0.5.1=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.29.5=py310haa95532_0
  - ipython=8.27.0=py310haa95532_0
  - isort=5.13.2=py310haa95532_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py310haa95532_0
  - jellyfish=1.0.1=py310h8ecf97c_1
  - jinja2=3.1.4=py310haa95532_1
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.23.0=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_core=5.7.2=py310haa95532_0
  - jupyterlab_pygments=0.2.2=py310haa95532_0
  - keyring=24.3.1=py310haa95532_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.0=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=2.2.0=py310haa95532_1
  - markupsafe=2.1.3=py310h2bbff1b_0
  - matplotlib=3.9.2=py310haa95532_0
  - matplotlib-base=3.9.2=py310he19b0ae_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py310haa95532_0
  - mistune=2.0.4=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - more-itertools=10.3.0=py310haa95532_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - multidict=6.1.0=py310h827c3e9_0
  - mypy_extensions=1.0.0=py310haa95532_0
  - nbclient=0.8.0=py310haa95532_0
  - nbconvert=7.16.4=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.2.1=py310haa95532_0
  - numexpr=2.10.1=py310h4cd664f_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - numpydoc=1.7.0=py310haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.15=h827c3e9_0
  - packaging=24.1=py310haa95532_0
  - pandas=2.2.2=py310h5da7b33_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py310haa95532_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.0.0=py310hb5480e2_0
  - pip=24.2=py310haa95532_0
  - platformdirs=3.10.0=py310haa95532_0
  - pluggy=1.0.0=py310haa95532_1
  - ply=3.11=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.12.1=py310haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py310haa95532_0
  - pyflakes=3.2.0=py310haa95532_0
  - pygithub=2.4.0=py310haa95532_0
  - pygments=2.15.1=py310haa95532_1
  - pyjwt=2.9.0=py310haa95532_0
  - pylint=3.2.7=py310haa95532_0
  - pylint-venv=3.0.3=py310haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py310h8cc25b3_0
  - pyparsing=3.2.0=py310haa95532_0
  - pyqt=5.15.10=py310hd77b12b_0
  - pyqt5-sip=12.13.0=py310h2bbff1b_0
  - pyqtwebengine=5.15.10=py310hd77b12b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.15=h4607a30_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.20.0=py310haa95532_0
  - python-lsp-black=2.0.0=py310haa95532_0
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.12.0=py310h9909e9c_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytoolconfig=1.2.6=py310haa95532_0
  - pytorch=2.3.1=cpu_py310h0ce1571_0
  - pytz=2024.1=py310haa95532_0
  - pyuca=1.2=py310haa95532_1
  - pywin32=305=py310h2bbff1b_0
  - pywin32-ctypes=0.2.2=py310haa95532_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=25.1.2=py310hd77b12b_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qt-main=5.15.2=h19c9488_11
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.3.1=py310haa95532_0
  - qtconsole=5.6.0=py310haa95532_0
  - qtpy=2.4.1=py310haa95532_0
  - referencing=0.30.2=py310haa95532_0
  - requests=2.32.3=py310haa95532_1
  - rich=13.7.1=py310haa95532_0
  - rope=1.12.0=py310haa95532_0
  - rpds-py=0.10.6=py310h636fa0f_1
  - rtree=1.0.1=py310h2eaa2aa_0
  - setuptools=72.1.0=py310haa95532_0
  - sip=6.7.12=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py310haa95532_0
  - sphinx=7.3.7=py310h827c3e9_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.10=py310haa95532_0
  - spyder=6.0.1=py310haa95532_0
  - spyder-kernels=3.0.0=py310h9909e9c_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - superqt=0.6.7=py310h9909e9c_0
  - sympy=1.13.2=py310haa95532_0
  - tabulate=0.9.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py310h9909e9c_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tomli=2.0.1=py310haa95532_0
  - tomlkit=0.13.2=py310haa95532_0
  - tornado=6.4.1=py310h827c3e9_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.11.0=py310haa95532_0
  - typing_extensions=4.11.0=py310haa95532_0
  - tzdata=2024b=h04d1e81_0
  - ujson=5.10.0=py310h5da7b33_0
  - unicodedata2=15.1.0=py310h2bbff1b_0
  - unidecode=1.3.8=py310haa95532_0
  - urllib3=2.2.3=py310haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - watchdog=4.0.1=py310haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - whatthepatch=1.0.2=py310haa95532_0
  - wheel=0.44.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wrapt=1.14.1=py310h2bbff1b_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yapf=0.40.2=py310haa95532_0
  - yarl=1.11.0=py310h827c3e9_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.20.2=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - msgpack==1.1.0
      - protobuf==5.28.3
      - pyarrow==18.0.0
      - qstylizer==0.2.2
      - ray==2.39.0
      - tensorboardx==2.6.2.2
